export const restaurantData = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "478661",
        name: "Rominus Pizza & Burger",
        uuid: "cc903de6-d663-432d-8f82-9a1b75e4e514",
        city: "12",
        area: "Jhotwara",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "9ec9ffd900c24ef751e2f34ba3d2fd4b",
        cuisines: [
          "Pizzas",
          "Italian",
          "Italian-American",
          "Fast Food",
          "Snacks",
          "American",
          "Desserts",
          "Beverages",
          "Bakery",
          "Continental",
        ],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 4.300000190734863,
        slugs: {
          restaurant: "rominus-pizza-and-burger-jhotwara-jhotwara",
          city: "jaipur",
        },
        cityState: "12",
        address:
          "G-10 GROUND floore krishna enclave beyond 200 feet bypass kalwar road jhotwara jaipur - 302012",
        locality: "Kalwar Road",
        parentId: 8387,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7396179~p=1~eid=00000189-2a87-bd61-35b6-480200210162~srvts=1688635686241",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "478661",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 4.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "306009",
        name: "Hotel Krishnam Palace And Restaurant",
        uuid: "75883264-953b-4761-aa55-15538e5abd61",
        city: "12",
        area: "Jhotwara",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "ywbucwbbxpo0ugaptvp0",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: "20 MINS",
        lastMileTravel: 1.399999976158142,
        slugs: {
          restaurant: "hotel\tkrishnam-palace-and-restaurant-jhotwara-jhotwara",
          city: "jaipur",
        },
        cityState: "12",
        address:
          "plot no 57,58 jai bhawani vihar Ist govindpura  near manglam city kalwar road jhotwara jaipur",
        locality: "Kalwar Road",
        parentId: 99853,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2300,
          message: "",
          title: "Delivery Charge",
          amount: "2300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "306009",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 1.399999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "570553",
        name: "New Kanha Restaurant",
        uuid: "dad67ada-e193-4cf6-aeb9-49ee30b5c8ad",
        city: "12",
        area: "Jhotwara",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "gtvb32623fmjte7nngk9",
        cuisines: ["North Indian", "Chinese", "Tandoor", "Snacks"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 1.2000000476837158,
        slugs: {
          restaurant: "new-kanha-restaurant-jhotwara-jhotwara-2",
          city: "jaipur",
        },
        cityState: "12",
        address:
          "Kamla Nagar, opp dal mills,Govindpura,Kalwar road,jhotwara jaipur",
        locality: "Kamla Nagar",
        parentId: 146925,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2300,
          message: "",
          title: "Delivery Charge",
          amount: "2300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "570553",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 1.2000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "632986",
        name: "La Pino'z Pizza",
        uuid: "9b76861b-4c74-472a-97cc-c3b81b72192f",
        city: "12",
        area: "Jhotwara",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "b9ixfa8dpbf19njypjbt",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 5.5,
        slugs: {
          restaurant: "la-pinoz-pizza-joshi-marg-chouraha-vaishali-nagar",
          city: "jaipur",
        },
        cityState: "12",
        address:
          "17,SHEKHAWATI PLAZA ,SANJAY NAGAR ,JOSHI MARG CHOURAHA ,MAIN KALWAR ROAD ,JHOTWARA",
        locality: "Kalwad Road",
        parentId: 4961,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4400,
          message: "",
          title: "Delivery Charge",
          amount: "4400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7213392~p=4~eid=00000189-2a87-bd61-35b6-480300210452~srvts=1688635686241",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "632986",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 5.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.8",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
  ];
export const Img_data="https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/"
